"""Profile suggestion — proposed update to company_profile.json from a KB doc.

Generated by the fact-extraction agent on KB ingestion. User reviews and
approves/rejects each suggestion individually on the Config page. Approved
suggestions write back to data/company_profile.json with a _meta.version
patch bump.
"""

from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import JSON, DateTime, ForeignKey, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin

if TYPE_CHECKING:
    from app.models.kb import KnowledgeBaseDocument


class ProfileSuggestion(Base, TimestampMixin):
    __tablename__ = "profile_suggestions"

    id: Mapped[int] = mapped_column(primary_key=True)
    kb_document_id: Mapped[int] = mapped_column(
        ForeignKey("knowledge_base_documents.id", ondelete="CASCADE"),
        index=True,
    )

    # Operation tells the apply logic what to do:
    #   append → push proposed_value onto the list at `section`
    #   merge  → find list entry where the entry's name/project matches
    #            match_key, then update its fields with proposed_value
    #   set    → replace profile[section] entirely with proposed_value
    operation: Mapped[str] = mapped_column(String(16), nullable=False)

    # Top-level key in company_profile.json: "key_personnel", "past_performance",
    # "certifications", "deep_specializations", "differentiators_for_proposals", etc.
    section: Mapped[str] = mapped_column(String(80), nullable=False)

    # For merge ops: identifier within the list (person name, project name, etc.)
    match_key: Mapped[str | None] = mapped_column(String(300), nullable=True)

    # The new value to append, the fields to merge in, or the value to set.
    # For lists of strings (certifications): a string.
    # For object lists (key_personnel, past_performance): a dict.
    proposed_value_json: Mapped[dict | list | str | None] = mapped_column(JSON, nullable=False)

    # Snapshot of what the profile holds today for context in the review UI.
    # For merges this is the current entry; for appends into a list of strings
    # it can be the existing list (so user sees what's already there).
    current_value_json: Mapped[dict | list | str | None] = mapped_column(JSON, nullable=True)

    # Human-readable summary shown in the review UI.
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    rationale: Mapped[str | None] = mapped_column(Text, nullable=True)

    status: Mapped[str] = mapped_column(
        String(16),
        default="pending",
        nullable=False,
        index=True,
    )
    reviewed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    reviewed_by: Mapped[str | None] = mapped_column(String(80), nullable=True)

    document: Mapped[KnowledgeBaseDocument] = relationship()
